name: .NET

on:
  push:
    branches: [ master ]
    paths: '5.0/Questionnaire/**'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0 Questionnaire
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore 5.0/Questionnaire/
    - name: Build
      run: dotnet build 5.0/Questionnaire/ --no-restore
    - name: Test
      run: dotnet test 5.0/Questionnaire/ --no-build --verbosity normal
